export const SET_ERRORS="setErrors";
export const SET_PRODUCT_PROPS="setProductProps";
export const SET_QUANTITY_SELECTED="setQuantitySelected";
export const SET_PAGE = "setPage";
export const SET_MAIN_PAGE = "setMainPage";
export const SET_COLLECTION_CATEGORIES = "setCollectionCategories";
export const SET_CATEGORY_PRODUCTS = "setCategoryProducts";
export const CLEAR_PRODUCTS = "clearProducts";
export const ADD_ITEM="addItem";
export const REMOVE_ITEM="removeItem";
export const CLEAR_CART="clearCart";
export const SET_ITEM="setItem";
export const TOGGLE_ANIMATION="toggleAnimation";
export const SET_CONFIRMED_ORDER="setOrder"
export const CLEAR_SEND_ORDER_RESULT= "clearSendOrderResult";
export const FULLFILL_ORDER="fullfillOrder";
export const SET_PAYMENT_FAILED="setPaymentFailed";
export const SET_FAILED_ORDER="setFailedOrder";

export const  SET_PAYMENT_SUCCESS="setPaymentSuccess";